-- AlterTable
ALTER TABLE `Doctor` ADD COLUMN `email` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `experiences` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `no_phone` VARCHAR(191) NOT NULL DEFAULT '';
