import type { Metadata } from "next";
import { Lato, Poppins } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";

const lato = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "300", "400", "700", "900"],
  variable: "--my-font-family",
});

export const metadata: Metadata = {
  title: "AppointMed",
  description: "Generated by create next app",
  icons: {
    icon: "public/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={lato.className} lang="en">
      <body style={{ overflowX: "hidden" }}>
        <AntdRegistry> {children}</AntdRegistry>
      </body>
    </html>
  );
}
